import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
export class AwsCdkTestStack extends cdk.Stack {
  
    // private readonly pipelineNotificationsTopic: Topic;
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
      super(scope, id, props);
    }

}   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               